POST http://localhost:3000/api/services
Content-Type: application/json

  {
      "name": "Decoração",
      "description": "Escolha a decoração para sua festa, e nós a montamos.",
      "price": 1400,
      "image": "https://images.unsplash.com/photo-1478146059778-26028b07395a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=892&q=80"
    }
###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/66ba59ec1e96ac4da3835850

###
DELETE http://localhost:3000/api/services/66ba59ec1e96ac4da3835850

###
PUT http://localhost:3000/api/services/66ba60f013f7cb22add43bc8
Content-Type: application/json

{
    "name": "TESTE ATUALIZAÇÃO",
    "description": "alguma descrição",
    "price": 2500,
    "image": "https://pixnio.com/pt/media/escritorio-trabalhando-secretario-mulher-computador-portatil#"
}
###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento",
    "author": "Matheus",
    "description": "uma festa de aniversário",
    "budget": 9000,
    "image": "https://pixnio.com/pt/media/escritorio-trabalhando-secretario-mulher-computador-portatil#",
    "services": [
    {     
        "name": "algum serviço 1",
        "description": "alguma descrição",
        "price": 3000,
        "image": "https://pixnio.com/pt/media/escritorio-trabalhando-secretario-mulher-computador-portatil#"
    },
    {
        "name": "algum serviço 2",
        "description": "alguma descrição",
        "price": 1600,
        "image": "https://pixnio.com/pt/media/escritorio-trabalhando-secretario-mulher-computador-portatil#"
    }
    ]
}
###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/66bba1225bdf70f73426e077
###
DELETE http://localhost:3000/api/parties/66bba1225bdf70f73426e077
###
PUT http://localhost:3000/api/parties/66bb9ff95bdf70f73426e075
Content-Type: application/json

{
    "title": "Meu evento",
    "author": "Matheus",
    "description": "uma festa de aniversário",
    "budget": 9000,
    "image": "https://pixnio.com/pt/media/escritorio-trabalhando-secretario-mulher-computador-portatil#",
    "services": [
    {     
        "name": "algum serviço 1",
        "description": "alguma descrição",
        "price": 3000,
        "image": "https://pixnio.com/pt/media/escritorio-trabalhando-secretario-mulher-computador-portatil#"
    },
    {
        "name": "algum serviço 2",
        "description": "alguma descrição",
        "price": 1600,
        "image": "https://depositphotos.com/br/photo/forest-9844164"
    }
    ]
}